---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: recolhe-eco-api-deployment
  namespace: recolhe-eco
  labels:
    name: recolhe-eco-api
spec:
  replicas: 1
  selector:
    matchLabels:
      name: recolhe-eco-api
  template:
    metadata:
      labels:
        name: recolhe-eco-api
    spec:
      containers:
        - name: recolhe-eco-api
          image: recolheeco/api:latest
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  labels:
    name: recolhe-eco-api
  name: recolhe-eco-api-service
  namespace: recolhe-eco
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: http
  selector:
    name: recolhe-eco-api
  type: ClusterIP
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: recolhe-eco-api-ingress
  namespace: recolhe-eco
spec:
  entryPoints:
    - web
  routes:
    - kind: Rule
      match: Host(`api.recolhe.eco`) && PathPrefix(`/`)
      services:
        - kind: Service
          name: recolhe-eco-api-service
          namespace: recolhe-eco
          passHostHeader: true
          port: 80
          responseForwarding:
            flushInterval: 1ms
          scheme: http
          strategy: RoundRobin
          weight: 10